#Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [5]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [6]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [7]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [10]:
y_train

array([5, 7, 5, ..., 6, 7, 5])

In [11]:
y_test

array([6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 7, 6, 6, 5, 5, 5, 6, 6, 5, 4,
       6, 7, 5, 6, 5, 6, 6, 7, 6, 7, 5, 7, 5, 5, 6, 6, 5, 6, 6, 4, 7, 6,
       6, 7, 6, 6, 5, 7, 7, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6, 5,
       5, 3, 6, 7, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 7, 6, 5, 5, 6, 6, 6, 5,
       6, 5, 5, 5, 8, 6, 5, 7, 5, 5, 5, 6, 7, 6, 5, 6, 7, 5, 5, 5, 5, 5,
       6, 7, 5, 7, 5, 5, 7, 7, 4, 6, 6, 6, 6, 6, 5, 5, 6, 6, 5, 7, 6, 6,
       7, 6, 6, 7, 7, 6, 7, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6,
       6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 7, 5, 5, 5, 5, 5, 6, 6, 5,
       5, 7, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6, 5, 7, 6, 5, 6, 5, 6, 5, 6,
       5, 7, 5, 6, 5, 5, 5, 5, 4, 6, 6, 5, 6, 6, 6, 7, 6, 6, 5, 5, 7, 7,
       6, 7, 5, 7, 7, 5, 4, 5, 6, 7, 5, 5, 6, 5, 7, 5, 5, 5, 5, 6, 6, 6,
       5, 7, 7, 6, 5, 6, 6, 6, 5, 4, 5, 5, 5, 7, 5, 6, 6, 4, 5, 7, 5, 5,
       7, 6, 6, 5, 6, 7, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6,
       6, 4, 6, 7, 5, 5, 6, 6, 8, 5, 5, 6, 7, 6, 6,

In [12]:
x_train

array([[ 7.5  ,  0.61 ,  0.2  , ...,  3.1  ,  0.4  ,  9.3  ],
       [10.   ,  0.31 ,  0.47 , ...,  3.36 ,  0.8  , 10.5  ],
       [ 9.2  ,  0.92 ,  0.24 , ...,  3.48 ,  0.54 ,  9.8  ],
       ...,
       [ 7.9  ,  0.545,  0.06 , ...,  3.36 ,  0.67 , 10.7  ],
       [ 7.2  ,  0.36 ,  0.46 , ...,  3.4  ,  0.85 , 11.   ],
       [ 7.5  ,  0.41 ,  0.15 , ...,  3.14 ,  0.58 ,  9.1  ]])

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [15]:
ntrain

array([[5],
       [7],
       [5],
       ...,
       [6],
       [7],
       [5]])

In [16]:

ntest

array([[6],
       [6],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [7],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [4],
       [6],
       [7],
       [5],
       [6],
       [5],
       [6],
       [6],
       [7],
       [6],
       [7],
       [5],
       [7],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
       [6],
       [4],
       [7],
       [6],
       [6],
       [7],
       [6],
       [6],
       [5],
       [7],
       [7],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [5],
       [3],
       [6],
       [7],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [7],
       [6],
       [5],
    

In [17]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [18]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [19]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [20]:
xn_train

array([[-0.46899973,  0.44868613, -0.35695651, ..., -1.39351295,
        -1.57236087, -1.07423128],
       [ 0.97364254, -1.2171181 ,  1.0419063 , ...,  0.31638261,
         0.90224405,  0.06277173],
       [ 0.51199701,  2.17001716, -0.14971757, ...,  1.10556518,
        -0.70624915, -0.60048002],
       ...,
       [-0.23817697,  0.08776188, -1.08229278, ...,  0.31638261,
         0.09799745,  0.25227223],
       [-0.6421168 , -0.93948406,  0.99009657, ...,  0.57944347,
         1.21156966,  0.53652299],
       [-0.46899973, -0.66185002, -0.61600518, ..., -1.13045209,
        -0.45878866, -1.26373178]])

In [21]:
xn_test

array([[-0.46899973,  0.2265789 , -1.28953171, ...,  0.31638261,
        -0.21132816,  0.34702248],
       [ 1.31987668,  2.72528523,  0.83466737, ..., -1.52504338,
        -0.52065378, -0.31622927],
       [-0.41129404,  1.44816866, -0.30514677, ..., -1.26198252,
        -1.32490038, -1.16898153],
       ...,
       [-0.75752818,  0.69855676, -0.56419544, ...,  0.38214783,
        -0.64438402, -0.69523027],
       [-1.16146802, -1.2726449 ,  1.09371603, ...,  0.84250432,
         0.7785138 , -0.12672877],
       [ 0.5697027 ,  0.44868613, -0.04609811, ..., -0.47279995,
        -0.21132816, -0.69523027]])

In [22]:
yn_train

array([[-0.77572759],
       [ 1.68619694],
       [-0.77572759],
       ...,
       [ 0.45523468],
       [ 1.68619694],
       [-0.77572759]])

In [23]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [24]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [25]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [26]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [27]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [29]:

from sklearn.metrics import r2_score

In [30]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [31]:
print(r, l, d, s, p)

0.4566645714556453 0.3282412202862216 -0.07140036955732065 0.3670679817318355 0.3282412202862214
